version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /server
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=pokepass
      - PGDATABASE=pokemon
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /server
    command: bash -c "npm install && npm run dev"

  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=pokes
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=pokespass
volumes:
  dbdata: